name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup
        run: sed -i "s/%NAME%/test/g" build.sc
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt mill
      - name: Install CIRCT
        uses: circt/install-circt@v1.1.1
        with:
          version: 'firtool-1.40.0'
          file-name: 'firrtl-bin-ubuntu-20.04.tar.gz'
      - name: SBT Test
        run: sbt test
      - name: mill Test
        run: mill _.test
