name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup
        run: sed -i "s/%NAME%/test/g" build.sc
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Setup Mill
        uses: jodersky/setup-mill@v0.2.3
        with:
          mill-version: 0.9.7
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: Install CIRCT
        uses: circt/install-circt@v1.1.1
        with:
          version: 'firtool-1.40.0'
          file-name: 'firrtl-bin-ubuntu-20.04.tar.gz'
      - name: SBT Test
        run: sbt test
      - name: mill Test
        run: mill _.test
